import { Dimensions, StyleSheet } from 'react-native';
import { Radius, Shadows, Spacing, Typography } from '@/theme';

const { width: SCREEN_W, height: SCREEN_H } = Dimensions.get('window');

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#000000',
  },
  cameraWrap: {
    flex: 1,
    position: 'relative',
  },
  camera: {
    flex: 1,
  },
  topControls: {
    position: 'absolute',
    top: Spacing.md,
    left: Spacing.md,
    right: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 20,
  },
  topIconBtn: {
    width: 42,
    height: 42,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeToggleRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    borderRadius: Radius.full,
    padding: 3,
  },
  modeBtn: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.full,
  },
  modeBtnActive: {
    backgroundColor: '#FFFFFF',
  },
  modeText: {
    fontSize: Typography.sizes.xs,
    fontWeight: Typography.weights.bold as any,
    color: '#FFFFFF',
  },
  modeTextActive: {
    color: '#000000',
  },
  scannerOverlayBox: {
    position: 'absolute',
    top: '18%',
    left: '8%',
    right: '8%',
    bottom: '22%',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: Radius.md,
    zIndex: 10,
    overflow: 'hidden',
  },
  laserLine: {
    height: 2.5,
    backgroundColor: '#00E676',
    width: '100%',
    shadowColor: '#00E676',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
  },
  hudBadge: {
    position: 'absolute',
    bottom: Spacing.md,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.full,
  },
  hudText: {
    color: '#FFFFFF',
    fontSize: Typography.sizes.xs,
    fontWeight: Typography.weights.semibold as any,
  },
  bottomControls: {
    position: 'absolute',
    bottom: Spacing.xl,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: Spacing.xl,
    zIndex: 20,
  },
  galleryThumbnailBtn: {
    width: 48,
    height: 48,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
  },
  shutterBtnOuter: {
    width: 76,
    height: 76,
    borderRadius: Radius.full,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 3,
  },
  shutterBtnInner: {
    width: '100%',
    height: '100%',
    borderRadius: Radius.full,
    backgroundColor: '#FFFFFF',
  },
  batchCounterBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FF3B30',
    borderRadius: Radius.full,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  batchCounterText: {
    color: '#FFFFFF',
    fontSize: Typography.sizes.xxs,
    fontWeight: Typography.weights.bold as any,
  },
  reviewRoot: {
    flex: 1,
  },
  reviewHeader: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerIconButton: {
    padding: Spacing.xs,
  },
  reviewTitle: {
    fontSize: Typography.sizes.md,
    fontWeight: Typography.weights.bold as any,
  },
  reviewBody: {
    flex: 1,
  },
  filtersContainer: {
    paddingVertical: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  filtersScroll: {
    paddingHorizontal: Spacing.md,
    gap: Spacing.xs,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.sm + 2,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.full,
    borderWidth: 1,
    gap: Spacing.xxs,
  },
  filterColorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  filterPillText: {
    fontSize: Typography.sizes.xs,
    fontWeight: Typography.weights.medium as any,
  },
  cropContainer: {
    flex: 1,
    position: 'relative',
  },
  reviewFooter: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: Spacing.sm,
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  actionIconBtn: {
    alignItems: 'center',
    gap: 4,
  },
  actionIconLabel: {
    fontSize: Typography.sizes.xxs,
    fontWeight: Typography.weights.semibold as any,
  },
  batchBarScroll: {
    gap: Spacing.xs,
    paddingVertical: Spacing.xs,
  },
  batchThumbItem: {
    width: 48,
    height: 64,
    borderRadius: Radius.xs,
    borderWidth: 1.5,
    overflow: 'hidden',
  },
  batchThumbImage: {
    width: '100%',
    height: '100%',
  },
  batchThumbBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  batchThumbNum: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: Typography.weights.bold as any,
  },
  ctaButtonsRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  permissionTitle: {
    fontSize: Typography.sizes.lg,
    fontWeight: Typography.weights.bold as any,
    textAlign: 'center',
  },
  permissionDesc: {
    fontSize: Typography.sizes.sm,
    textAlign: 'center',
    lineHeight: 22,
  },
});
